apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: rthy86sqx-dotnet-basic-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/rthy86sqx-dotnet-basic-gitops